### ISSUE TITLE
Random error about Object Reference suddenly showing up in Dalamud Log.

### ISSUE THREAD

**Issue by Maxunit** [NightmareXIV/XIVInstantMessenger#17]
I never had the following error show up in my dalamud log until the recent 6.35 update and no idea if it might have an impact on XIM's functionality, but the error is:

```
02:16:33.029 | ERR [ECommons] [XIV Instant Messenger] Object reference not set to an instance of an object.
   at Messenger.Messenger.DecodeSender(SeString sender, Sender& senderStruct) in /work/repo/Messenger/Messenger.cs:line 463
   at Messenger.Messenger.OnChatMessage(XivChatType type, UInt32 senderId, SeString& sender, SeString& message, Boolean& isHandled) in /work/repo/Messenger/Messenger.cs:line 361
02:16:36.190 | ERR [ECommons] [XIV Instant Messenger] Object reference not set to an instance of an object.
   at Messenger.Messenger.DecodeSender(SeString sender, Sender& senderStruct) in /work/repo/Messenger/Messenger.cs:line 463
   at Messenger.Messenger.OnChatMessage(XivChatType type, UInt32 senderId, SeString& sender, SeString& message, Boolean& isHandled) in /work/repo/Messenger/Messenger.cs:line 361
```

No idea when exactly it happens and why. I only notice it from time to time whenever I idle around and check my log out of habit every now and then.

Thought I'd report it, just in case.

**Comment by Limiana** [comment]
Could not reproduce this issue, I'm assuming it was something to do with one of Dalamud updates
